[env]
OUT_DIR = "target/wasm32-unknown-unknown"
CARGO_BIN_NAME = "honey_os"

[tasks.mk_dist]
description = "Make the dist folder if it doesn't exist"
command = "mkdir"
args = ["-p", "dist"]

[tasks.build_release]
description = "Build the project"
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.build_dev]
description = "Build the project"
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown"]

[tasks.bindgen]
description = "Generate the bindings"
command = "wasm-bindgen"
args = [
    "${OUT_DIR}/${@}/${CARGO_BIN_NAME}.wasm",
    "--target",
    "web",
    "--out-dir",
    "dist",
]

[tasks.copy_www]
linux_alias = "unix_copy_www"
mac_alias = "unix_copy_www"
windows_alias = "windows_copy_www"

[tasks.unix_copy_www]
description = "Copy the www folder"
command = "cp"
args = ["-r", "www/", "dist/"]

[tasks.windows_copy_www]
description = "Copy the www folder"
command = "copy"
args = ["www/", "dist/", "/Y"]

[tasks.dist]
description = "Distribute the project"
dependencies = ["mk_dist", "build_release", "bindgen", "copy_www"]

[tasks.dist-dev]
description = "Distribute the project"
dependencies = ["mk_dist", "build_dev", "bindgen", "copy_www"]

[tasks.dev]
description = "Watch the project"
command = "python"
args = ["devtools/dev.py"]
