[build]
target = ["wasm32-unknown-unknown"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals"]
runner = 'wasm-bindgen-test-runner'

[unstable]
build-std = ["panic_abort", "std"]
